#!/usr/bin/env bash
# https://github.com/borisguery/git-keywords-checker
disallowed="nocheckin NOCHECKIN"

git diff --cached --name-status | while read x file; do
        if [ "$x" == 'D' ]; then continue; fi
        for word in $disallowed
        do
            if egrep $word $file ; then
                echo ""
                echo "ERROR: Disallowed expression \"${word}\" in file: ${file}"
                echo ""
                exit 1
            fi
        done
done || exit $?
